# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox
import cv2
import numpy as np
import sys
import snap7
import snap7.client
from pyzbar import pyzbar
import time
from PyQt5.QtSql import QSqlDatabase, QSqlQuery
import mysql.connector

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(833, 837)
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 831, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(25)
        self.lineEdit.setFont(font)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setFrame(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 70, 831, 201))
        self.frame.setStatusTip("")
        self.frame.setAccessibleName("")
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.frame.setInputMethodHints(QtCore.Qt.ImhNone)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 261, 201))
        self.frame_2.setStyleSheet("background-color:rgb(255, 170, 127)\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setLineWidth(2)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(85, 0, 255)")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.ip_plc = QtWidgets.QLineEdit(self.frame_2)
        self.ip_plc.setGeometry(QtCore.QRect(10, 120, 141, 21))
        self.ip_plc.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.ip_plc.setText("")
        self.ip_plc.setObjectName("ip_plc")
        self.bt_on = QtWidgets.QPushButton(self.frame_2)
        self.bt_on.setGeometry(QtCore.QRect(160, 70, 75, 24))
        self.bt_on.setStyleSheet("background-color:green")
        self.bt_on.setObjectName("bt_on")
        self.bt_connect = QtWidgets.QPushButton(self.frame_2)
        self.bt_connect.setGeometry(QtCore.QRect(160, 120, 75, 24))
        self.bt_connect.setStyleSheet("background-color:green")
        self.bt_connect.setObjectName("bt_connect")
        self.bt_off = QtWidgets.QPushButton(self.frame_2)
        self.bt_off.setGeometry(QtCore.QRect(160, 70, 75, 24))
        self.bt_off.setStyleSheet("background-color:red\n"
"")
        self.bt_off.setObjectName("bt_off")
        self.camera = QtWidgets.QComboBox(self.frame_2)
        self.camera.setGeometry(QtCore.QRect(10, 70, 141, 22))
        self.camera.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.camera.setObjectName("camera")
        self.bt_disconnect = QtWidgets.QPushButton(self.frame_2)
        self.bt_disconnect.setGeometry(QtCore.QRect(160, 120, 75, 24))
        self.bt_disconnect.setStyleSheet("background-color:red")
        self.bt_disconnect.setObjectName("bt_disconnect")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(570, 0, 261, 201))
        self.frame_5.setStyleSheet("background-color: rgb(255, 170, 255)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setLineWidth(2)
        self.frame_5.setObjectName("frame_5")
        self.slider_threshold = QtWidgets.QSlider(self.frame_5)
        self.slider_threshold.setGeometry(QtCore.QRect(10, 80, 160, 22))
        self.slider_threshold.setMaximum(200)
        self.slider_threshold.setProperty("value", 100)
        self.slider_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold.setObjectName("slider_threshold")
        self.value_threshold = QtWidgets.QLineEdit(self.frame_5)
        self.value_threshold.setGeometry(QtCore.QRect(190, 80, 51, 22))
        self.value_threshold.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.value_threshold.setText("")
        self.value_threshold.setObjectName("value_threshold")
        self.line = QtWidgets.QFrame(self.frame_5)
        self.line.setGeometry(QtCore.QRect(10, 110, 231, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(85, 0, 255)")
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(70, 50, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setEnabled(True)
        self.frame_3.setGeometry(QtCore.QRect(270, 0, 291, 201))
        self.frame_3.setToolTip("")
        self.frame_3.setStyleSheet("background-color: rgb(85, 170, 255)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.bt_scan = QtWidgets.QPushButton(self.frame_3)
        self.bt_scan.setGeometry(QtCore.QRect(100, 140, 93, 28))
        self.bt_scan.setAutoFillBackground(False)
        self.bt_scan.setStyleSheet("background-color:#c1c1c1\n"
"")
        self.bt_scan.setObjectName("bt_scan")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(85, 0, 255)")
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(120, 50, 49, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.sw_auto = QtWidgets.QPushButton(self.frame_3)
        self.sw_auto.setGeometry(QtCore.QRect(50, 80, 93, 28))
        self.sw_auto.setAutoFillBackground(False)
        self.sw_auto.setStyleSheet("background-color:#c1c1c1\n"
"")
        self.sw_auto.setObjectName("sw_auto")
        self.sw_manual = QtWidgets.QPushButton(self.frame_3)
        self.sw_manual.setGeometry(QtCore.QRect(150, 80, 93, 28))
        self.sw_manual.setAutoFillBackground(False)
        self.sw_manual.setStyleSheet("background-color:#c1c1c1\n"
"")
        self.sw_manual.setObjectName("sw_manual")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(0, 281, 831, 431))
        self.frame_9.setStyleSheet("background-color:  rgb(234, 234, 234);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_9.setLineWidth(2)
        self.frame_9.setObjectName("frame_9")
        self.lb_origin = QtWidgets.QLabel(self.frame_9)
        self.lb_origin.setGeometry(QtCore.QRect(10, 10, 401, 371))
        self.lb_origin.setAutoFillBackground(False)
        self.lb_origin.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lb_origin.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lb_origin.setText("")
        self.lb_origin.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_origin.setObjectName("lb_origin")
        self.lb_xla = QtWidgets.QLabel(self.frame_9)
        self.lb_xla.setGeometry(QtCore.QRect(420, 10, 401, 371))
        self.lb_xla.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lb_xla.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lb_xla.setText("")
        self.lb_xla.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_xla.setObjectName("lb_xla")
        self.curent_data_2 = QtWidgets.QLabel(self.frame_9)
        self.curent_data_2.setGeometry(QtCore.QRect(10, 390, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.curent_data_2.setFont(font)
        self.curent_data_2.setStyleSheet("color: rgb(0, 0, 255);")
        self.curent_data_2.setAlignment(QtCore.Qt.AlignCenter)
        self.curent_data_2.setObjectName("curent_data_2")
        self.curent_data_3 = QtWidgets.QLabel(self.frame_9)
        self.curent_data_3.setGeometry(QtCore.QRect(420, 390, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.curent_data_3.setFont(font)
        self.curent_data_3.setStyleSheet("color: rgb(0, 0, 255);")
        self.curent_data_3.setAlignment(QtCore.Qt.AlignCenter)
        self.curent_data_3.setObjectName("curent_data_3")
        self.communication = QtWidgets.QFrame(self.centralwidget)
        self.communication.setGeometry(QtCore.QRect(0, 720, 831, 111))
        self.communication.setStyleSheet("background-color:  rgb(234, 234, 234);")
        self.communication.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.communication.setFrameShadow(QtWidgets.QFrame.Raised)
        self.communication.setObjectName("communication")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.communication)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setGeometry(QtCore.QRect(280, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(85, 0, 255)")
        self.lineEdit_8.setFrame(False)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_3 = QtWidgets.QLabel(self.communication)
        self.label_3.setGeometry(QtCore.QRect(130, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.communication)
        self.label_4.setGeometry(QtCore.QRect(130, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.communication)
        self.label_5.setGeometry(QtCore.QRect(580, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setText("")
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.communication)
        self.label_6.setGeometry(QtCore.QRect(580, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "Digital image processing"))
        self.lineEdit_4.setText(_translate("MainWindow", "SETTING"))
        self.ip_plc.setPlaceholderText(_translate("MainWindow", "192.168.0.1"))
        self.bt_on.setText(_translate("MainWindow", "Turn on"))
        self.bt_connect.setText(_translate("MainWindow", "Connect"))
        self.bt_off.setText(_translate("MainWindow", "Turn off"))
        self.bt_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.lineEdit_7.setText(_translate("MainWindow", "OPTIONS"))
        self.label_2.setText(_translate("MainWindow", "THRESSHOLD"))
        self.bt_scan.setText(_translate("MainWindow", "SCAN"))
        self.lineEdit_6.setText(_translate("MainWindow", "PANEL"))
        self.label.setText(_translate("MainWindow", "MODE"))
        self.sw_auto.setText(_translate("MainWindow", "AUTO"))
        self.sw_manual.setText(_translate("MainWindow", "MANUAL"))
        self.curent_data_2.setText(_translate("MainWindow", "ORIGINAL IMAGE"))
        self.curent_data_3.setText(_translate("MainWindow", "PROCESSED IMAGE"))
        self.lineEdit_8.setText(_translate("MainWindow", "COMMUNICATION"))
        self.label_3.setText(_translate("MainWindow", "DATA ON PLC :"))
        self.label_6.setText(_translate("MainWindow", "DATA SCANED :"))
        # ---------------------------------------------------------------------BẮT ĐẦU----------------------------------------------------------------
        self.ip_plc.setText('192.168.1.15')
        self.bt_off.setVisible(False)
        self.bt_disconnect.setVisible(False)
        self.value_threshold.setText(str(self.slider_threshold.value()))
        self.sw_manual.setStyleSheet("background-color: blue")
        self.bt_scan.setVisible(True)
        self.mode = 0
        self.bt_scan.setDisabled(True)
        self.sw_auto.setDisabled(True)
        self.sw_manual.setDisabled(True)
        self.thread = {}
        # Thiết lập kết nối tới csdl MySQL
        self.mydb = mysql.connector.connect(
            host="localhost",
            user="root",
            password="012321323Vn",
            database="python_project_1"
        )
        # Kiểm tra kết nối
        if self.mydb.is_connected():
            print("Kết nối thành công tới mysql!")
        else:
            print("Kết nối không thành công!")
        # Lấy danh sách thiết bị camera
        self.get_camera_list()
        # Kết nối sự kiện click của nút "on" với hàm xử lý
        self.bt_on.clicked.connect(self.turnon_camera)
        self.bt_off.clicked.connect(self.turnoff_camera)
        self.bt_connect.clicked.connect(self.connect_plc)
        self.bt_disconnect.clicked.connect(self.disconnect_plc)
        self.slider_threshold.valueChanged.connect(self.value_slider_change)
        self.value_threshold.returnPressed.connect(self.update_value_thresshold)
        self.sw_manual.clicked.connect(lambda:self.change_mode(0))
        self.sw_auto.clicked.connect(lambda:self.change_mode(1))
        self.bt_scan.clicked.connect(self.event_scan)
    # ---------------------------------------------------------------------------------------------------------------
    def event_scan(self):
        self.read_qr_code(self.img_origin)
    def change_mode(self,value):
        if value == 0:          #manual
            self.sw_manual.setStyleSheet("background-color: blue")
            self.sw_auto.setStyleSheet("background-color:#c1c1c1")
            self.bt_scan.setVisible(True)
            self.lb_xla.clear()
            self.mode = 0
        else:                   #auto               
            self.sw_auto.setStyleSheet("background-color: blue")
            self.sw_manual.setStyleSheet("background-color:#c1c1c1")
            self.bt_scan.setVisible(False)
            self.mode = 1

    def update_value_thresshold(self):
        self.slider_threshold.setValue(int(self.value_threshold.text()))
    def value_slider_change(self):
        self.value_threshold.setText(str(self.slider_threshold.value()))
    def get_camera_list(self):
        camera_list = []
        index = 0
        while True:
            # Thử mở camera với từng index cho đến khi không thể mở
            cap = cv2.VideoCapture(index)
            if not cap.isOpened():
                break
            else:
                # Lấy thông tin thiết bị camera và thêm vào danh sách
                camera_info = f"Camera {index}: {cap.getBackendName()}"
                camera_list.append(camera_info)
                cap.release()
            index += 1
        self.camera.addItems(camera_list)
    def turnoff_camera(self):
        self.bt_on.setVisible(True)
        self.bt_off.setVisible(False)
        self.camera.setDisabled(False)
        self.stop_capture_video()
    def turnon_camera(self):
        global camera_index 
        camera_index = self.camera.currentIndex()
        print("Connecting camera " + str(camera_index) + "....")
        self.bt_on.setVisible(False)
        self.bt_off.setVisible(True)
        self.camera.setDisabled(True)
        self.bt_scan.setDisabled(False)
        self.sw_auto.setDisabled(False)
        self.sw_manual.setDisabled(False)
        self.start_capture_video()

    def start_capture_video(self):
        self.thread[1] = capture_video(index=1)
        self.thread[1].start()
        self.thread[1].signal.connect(self.show_webcam)
    def closeEvent(self, event):
        self.stop_capture_video()
        self.lb_origin.clear()
        self.lb_xla.clear()
    def stop_capture_video(self):
        self.thread[1].stop()
        self.lb_origin.clear()
        self.lb_xla.clear()
    def show_webcam(self,img):
        """Updates the image_label with a new opencv image"""
        rgb_image = self.convert_cv_qt(img)
        h, w, ch = rgb_image.shape
        bytes_per_line = ch * w
        convert_to_Qt_format = QtGui.QImage(rgb_image.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)
        p = convert_to_Qt_format.scaled(400, 300, QtCore.Qt.KeepAspectRatio)
        qt_img = QtGui.QPixmap.fromImage(p)
        self.lb_origin.setPixmap(qt_img)
        self.show_xla(rgb_image)

    def show_xla(self,img):
        # img = self.convert_hsv(img)
        img = self.convert_gray(img)
        img = self.convert_to_binary(img,self.slider_threshold.value())
        img = self.read_qr_code(img)
        if self.mode == 1:
            if (img.ndim == 2):
                h, w = img.shape
                bytes_per_line = w
            else:
                h, w, ch = img.shape
                bytes_per_line = ch * w
            convert_to_Qt_format = QtGui.QImage(img.data, w, h, bytes_per_line, QtGui.QImage.Format_Grayscale8)
            p = convert_to_Qt_format.scaled(400, 300, QtCore.Qt.KeepAspectRatio)
            qrcode_img = QtGui.QPixmap.fromImage(p)
            self.lb_xla.setPixmap(qrcode_img)

    #------------------------------------------------------------Xử lý ảnh----------------------------------------------------------------
    def convert_cv_qt(self, cv_img):
        return cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)

    def convert_hsv(self,img):
        return cv2.cvtColor(img,cv2.COLOR_RGB2HSV)
    
    def convert_gray(self,img):
        return cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
    
    def convert_to_binary(self, img, threshold):
        _, binary_image = cv2.threshold(img, threshold, 255, cv2.THRESH_BINARY)
        return binary_image

    def read_qr_code(self,img):
        barcodes = pyzbar.decode(img)
        for barcode in barcodes:                #lấy thông tin từng barcode từ những barcodes
            (x,y,w,h) = barcode.rect                                #lay thong tin kích thước để vẽ hinh chu nhat
            cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)       #ve hinh chu nhat lên bức ảnh
            barcodeData = barcode.data.decode("utf-8")              #Lấy thông tin dữ liệu mà barcode mã hóa
            barcodeType = barcode.type                              #kiểu barcode
            # text = "{} - {} ".format(barcodeData,barcodeType)       #tổng hợp thông tin từ barcode vào biến text
            text = barcodeData
            print(text)                                             #in dữ liệu lấy được từ barcode lên terminal để xem
            self.label_5.setText(text)
            myOutput = text
            myColor = (255,255,0)
            cv2.putText(img,myOutput,(x-10,y-10),cv2.FONT_HERSHEY_SIMPLEX,1,myColor,3)        #hiển thị chữ lên barcode trên ảnh
        return img

    #------------------------------------------------------------Kết thúc xử lý ảnh----------------------------------------------------------------
    def __init__(self):
        self.plc = snap7.client.Client()
    def connect_plc(self):
        # Kết nối tới PLC S7-1200
        # self.plc = snap7.client.Client()
        ip = self.ip_plc.text()
        if ip == "":
            print("Vui lòng nhập địa chỉ ip!")
        else:
            try:
                self.plc.connect(ip, 0, 1)
                print("Kết nối thành công tới PLC!")
                self.bt_connect.setVisible(False)
                self.bt_disconnect.setVisible(True)
                self.ip_plc.setDisabled(True)
                self.start_plc()
            except Exception as e:
                print("Lỗi kết nối tới PLC:", str(e))
    def disconnect_plc(self):
        # Ngắt kết nối PLC
        try:
            self.thread[2].stop()
            self.plc.disconnect()
            print("Ngắt kết nối thành công!")
            self.bt_connect.setVisible(True)
            self.bt_disconnect.setVisible(False)
            self.ip_plc.setDisabled(False)
        except Exception as e:
            print("Lỗi khi ngắt kết nối:", str(e))
    def start_plc(self):
        self.thread[2] = read_plc(index=2)
        self.thread[2].start()
        self.thread[2].signal.connect(self.plc_communication)
    
    # Ghi giá trị vào một biến trong PLC
    def write_plc_variable(self,variable_name, value):
        data = bytearray(snap7.util.get_real(value))
        self.plc.write_area(snap7.types.Areas.DB, 1, 0, data)  # Ghi 4 byte vào DB1, offset 0
        print(f'{variable_name} đã được ghi với giá trị: {value}')
    
    def plc_communication(self):
        print('alo')
class read_plc(QtCore.QThread):
    signal = QtCore.pyqtSignal(int)
    def __init__(self, ui , index = 0):
        self.ui = ui
    def __init__(self, index = 0):
        self.index = index
        print("start threading", self.index)
        super(read_plc, self).__init__()
    def run(self):
        while True:
            bool = self.read_plc_variable(1,'bool',1,78,3)              #Tag bool (DB: 1, ofset: 78.3)
            string = self.read_plc_variable(10,'string', 1, 66, 10)     #Tag string [10] (DB: 1, ofset: 66.0 )
            ui.label_4.setText(string)
            print('------------------------')
            print('Tag_bool: '+str(bool) +'\n'+'Tag_string: '+ string )
            print('------------------------')
            if(bool == True):
                cursor = ui.mydb.cursor()
                # SELECT
                cursor.execute("SELECT * FROM pre_data")
                # Lấy tất cả các dòng dữ liệu từ kết quả truy vấn
                result = cursor.fetchall()
                for row in result:
                    column2_value = row[1]  # Cột 2 có chỉ số 1
                cursor.close()
                self.write_string_plc_variable(1,66,10,str(ui.label_5.text()))
                self.write_bool(1,78,3,False)
            time.sleep(1)

    def stop(self):
        print("stop threading", self.index)
        self.terminate()
        
        # Đọc giá trị từ một biến trong PLC
    def read_plc_variable(self, length, variable_name, DB, offset, address):
        data = ui.plc.read_area(snap7.types.Areas.DB, DB, offset, length)  # Đọc dữ liệu từ DB
        if(length == 1):
            value = snap7.util.get_bool(data,0,address)         # Đọc tag là bool  
        elif(length > 1):  
            value = snap7.util.get_string(data,0)      # Đọc tag là chuỗi
        return value

    def write_string_plc_variable(self,db, start, size_string, string): 
        byte_array = bytearray(10)  # Khởi tạo bytearray với độ dài 10
        snap7.util.set_string(byte_array, 0, string, size_string )  # Chuyển đổi chuỗi thành bytearray
        ui.plc.db_write(db, start, byte_array)  # Ghi bytearray vào PLC
        print("Đã ghi dữ liệu chuỗi vào PLC thành công.")
    
    def write_bool(self,db_num,start_byte,boolean_index,bool_value): #Bool yazma 
        data = bytearray(1)
        snap7.util.set_bool(data,0,boolean_index,bool_value)
        ui.plc.db_write(db_num,start_byte,data)
    

class capture_video(QtCore.QThread):
    signal = QtCore.pyqtSignal(np.ndarray)
    def __init__(self, index):
        self.index = index
        print("start threading", self.index)
        super(capture_video, self).__init__()
    def run(self):
        global camera_index
        cap = cv2.VideoCapture(camera_index)
        while True:
            ret,img = cap.read()
            if ret:
                self.signal.emit(img)
    def stop(self):
        print("stop threading", self.index)
        self.terminate()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    class_plc = read_plc()
    read_plc(ui)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
